### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by alex-bender** [marcjourneux/pylox#1]
Hi! It looks impressive, a lot of things implemented. Is that everything what was in the book or have you added something more?
I'd like to read the CI book as well, so I've checked python implementations from that page: https://github.com/munificent/craftinginterpreters/wiki/Lox-implementations
Great job. Hope that I would be able to refer to that repo in case I'm stuck.
Thanks!

**Comment by marcjourneux** [comment]
Hello,

yes everything from the book is there, plus a little side stuff (from the book as well). Feel free to improve it !
thanks
Marc
